<?php 
    header("Content-Type: text/html;charset=utf-8"); 
    if ($_REQUEST['cod']==1) 
        echo "<strong>Aries:</strong> Preserva tu espíritu natural de lucha, Aries, es tu mejor arma para conseguir ser alguien en la vida. Si todavía no te has convencido de ello, te irá bien hoy hacer una llamada a esa persona a la que consideras un genio y sabes que te aprecia. Está dispuesta a ayudarte a diario y tendrá un buen consejo para ti. Escúchale con atención porque te puede dar la clave definitiva. Es posible que recibas hoy un dinero con el que no contabas. Revisa esos números de lotería que llevas en el billetero y de los que no te acordabas, afortunada Aries. En el terreno sentimental, si no puedes quitarte de la cabeza a diario a una persona que está siendo cada vez más especial para ti, atrévete a dar el primer paso, que estamos en el siglo XXI y no tienes por qué esperar a que sea él quien tome la iniciativa. Envíale un mensajito afectuoso, tampoco es necesario que muestres todas tus cartas. Por su respuesta sabrás si es la persona correcta o no."; 
    if ($_REQUEST['cod']==2) 
        echo "<strong>Tauro:</strong> Echa un vistazo hacia el pasado reciente, Tauro, revisa hoy si el balance de lo que has hecho por tu vida profesional en las últimas semanas es positivo. Recuerda que has de comprometerte más con lo que te has propuesto si quieres alcanzar resultados positivos. Hoy puedes tener un momento genial con tus amigos más íntimos. Si algo no te ha salido como esperabas puedes desahogarte con ellos y contarles en confianza tus problemas. Encontrarás calor y comprensión. En el amor, no hagas caso en ningún momento de terceras personas que no aportan nada positivo a tu relación. Ahora estás en una excelente etapa para tu vida sentimental, sobre todo si llevas ya mucho tiempo con una persona. Aunque te falte tiempo, Tauro, préstale a diario la atención que necesita, porque puede que él no se atrreva a pedírtela. Presta más atención a las señales, en especial en el terreno amoroso. Afina tu intuición y tendrás más aciertos."; 
    if ($_REQUEST['cod']==3) 
        echo "<strong>Géminis:</strong> Te espera hoy una excelente jornada profesional, Géminis, y muy buena también en los negocios o pactos. Si estás pensando en realizar una venta o asociarte con alguien, hoy es el día ideal para concretar los detalles, firmar contratos o papeleo, pero no estará de más que leas muy bien lo que firmes. También la letra pequeña, que es donde surgen los problemas. Estás en una situación insuperable, pero mantén los ojos bien abiertos a diario para que no se escapen las oportunidades que se cruzan en tu camino. En el terreno amoroso, estás en el momento ideal para volver a enamorarte, Géminis. Si se te presenta la ocasión, no dejes de hacerlo por temor a un nuevo fracaso. Deja estos miedos que a diario te quitan las ganas de encontrar a alguien. Si tienes buena disposición y te lo propones, darás con la persona adecuada. Aleja los temores a volver a equivocarte, has aprendido ya bastante de los errores cometidos."; 
    if ($_REQUEST['cod']==4) 
        echo "<strong>Cancer:</strong> Aunque todo te funciona a pedir de boca, no eches las campanas al vuelo todavía, Cáncer. Es verdad que has conseguido muchas cosas, pero aún no es el momento de celebrarlo. Todavía queda mucho por hacer a diario y tienes que seguir luchando. Si hoy alguien que no es de tu entorno de confianza te propone invertir un dinerito en un negocio o algún producto bancario, recuerda que tú ya habías contemplado esta posibilidad anteriormente. Si aceptas te puede reportar buenos beneficios. Pide hoy consejo a tu pareja, ten más confianza en su criterio. Además, él tiene un gran interés en que todo te salga bien, aunque a ti te cueste reconocerlo. Sería un puntazo que tuvieras ahora un detalle con tu chico. Él no te lo va a pedir, pero tú le conoces bien y no es necesario que te diga lo que espera de ti. Si llevas mucho tiempo de relación, Cáncer, intenta poner a diario un poquitín más de chispa, evita caer en unos hábitos rutinarios."; 
        if ($_REQUEST['cod']==5) 
            echo "<strong>Leo:</strong> Dale más importancia a lo que consigues a diario, Leo. Tu carácter es fuerte, pero temiendo pecar de soberbia, a veces muestras una modestia mal entendida que te hace parecer excesivamente humilde. Vale que no te creas la reina del mambo, pero tampoco que parezca que te subvaloras y transmitas esta sensación a los que te rodean. Reconoce hoy tus logros, por pequeños que sean, y disfrútalos mientras esperas que llegue tu gran momento, cuando puedas alcanzar este objetivo que tienes en tu mente a diario desde hace tiempo. En el terreno profesional, aprende a cambiar el rumbo cuando algo te resulte imposible de manejar. Y no pienses en las cosas que no has logrado, Leo, mantén hoy tu mente en las metas del futuro. No te quejes por los pequeños contratiempos que encuentras por el camino, la vida te sonríe, aunque quizá no tanto como quisieras. En el amor, recuerda que hay que alimentarlo siempre con cariño y mucha pasión."; 
        if ($_REQUEST['cod']==6) 
            echo "<strong>Virgo:</strong>Puedes tener que enfrentarte hoy a ciertas dificultades en el trabajo, Virgo. Será positivo para ti porque podrás aprender de esta experiencia, te harás más fuerte y le sacarás partido a diario, aunque quizá tardes un poco en darte cuenta. No te lamentes ni te vengas abajo por esta tontería. Si sientes que te afecta más de lo que debería, llama a tu mejor amiga para encontraros a la salida del trabajo y cuéntale lo que te pasa, háblale de esos temores infundados que te pueden arruinar el día. No te lo calles, libérate. Simplemente hablando verás como ese peso se aligera. Exteriorizando los temores te darás cuenta de que no hay para tanto. En el amor, no sigas pensando a diario en esa persona a la que dejaste en el pasado. Es lo que te impide tener de nuevo ganas para iniciar otra etapa. Has de pasar página, Virgo. Sólo si cierras este capítulo tendrás el camino abierto para encontrar a ese ser especial que está esperando por ti en alguna parte."; 
        if ($_REQUEST['cod']==7) 
            echo "<strong>Libra:</strong>Tienes un gran espíritu de lucha, Libra, y eres capaz de sobreponerte a diario a todos los obstáculos que podrían hacerte retroceder. Levántate hoy con el ánimo de afrontar una situación que quizá te está costando de superar más de lo habitual. Tendrás la fuerza y la energía suficiente para lograrlo. Puede que todo se deba a que recientemente has tomado alguna decisión equivocada. Observa con más detenimiento a diario lo que ocurre a tu alrededor, que no se te escape ningún detalle. En el terreno sentimental, Libra, si todavía estás sentimentalmente sola tal vez es porque estás buscando un ideal que no existe. Nadie es perfecto y es hora de que empieces a valorar hoy mismo si pesa más lo bueno que tiene ese pretendiente que te anda rondando desde hace tiempo. Para las Acuario que están enamoradas y son correspondidas, lo mejor es intentar preservar a diario las cosas positivas de este amor de cara al futuro. Alégrate de tu suerte."; 
        if ($_REQUEST['cod']==8) 
            echo "<strong>Escorpio:</strong>Hoy, Escorpio, puedes recibir una muy buena noticia respecto a tu trabajo. Quizá te llegue por fin el reconocimiento a tu constancia y tu empeño diario. Si habías perdido la esperanza y todo te parecía monótono y sin posibilidad de cambios en el futuro, ahora verás que hay mucho camino por recorrer todavía. Sigue esforzándote, pero no descuides a esa persona especial que tienes a tu lado por atender exclusivamente al trabajo a diario. Establece prioridades y dale a tu chico el lugar que le corresponde. Hoy es buen momento para averiguar si el amor que sientes es plenamente correspondido. Háblale de tus intenciones de cara al futuro, de lo que deseas conseguir en este terreno más personal. Si muestra entusiasmo, lánzate de cabeza, Escorpio. Pero si no te da una respuesta clara, quizá no es la persona apropiada para ser tu media naranja. De todas formas, dale un poco más de tiempo, quizá sólo es que no tiene las ideas claras todavía."; 
        if ($_REQUEST['cod']==9) 
            echo "<strong>Sagitario:</strong>Sabes muy bien lo que quieres, Sagitario, y también cómo conseguirlo. Tú eres la única responsable a la hora de elegir el camino acertado que te conduzca al objetivo que te has propuesto a diario. No te dejes arrastrar por las circunstancias a otros lugares donde no quieres estar. Hoy es el día apropiado para reflexionar sobre esto y decidir dejar a un lado todos los temores que te frenan en tu camino hacia el éxito. Ahora se dan todos los requisitos para dar el gran paso en tu vida, pero no parece que lo reconozcas, despistada Sagitario. Tampoco te dejes influenciar hoy por la persona que tienes al lado y que se supone tiene que apoyarte a diario. Si no lo hace y además intenta convencerte con sus ideas, ponle límites. Amar no es tener que supeditarte o adoptar su forma de pensar. Si su amor es sincero, te hablará de lo que cree que esá equivocado o que puedes mejorar, pero te alentará a que sigas luchando por tus metas."; 
        if ($_REQUEST['cod']==10) 
            echo "<strong>Capricornio:</strong>Las nativas de Capricornio vivirán hoy un intenso día en su vida sentimental. Prepárate, tanto si tienes pareja como si todavía estás sentimentalmente libre, Si perteneces a este signo astral, esta jornada está marcada por el amor. Si tienes una relación estable, hoy quizá se te plantee algún problema, especialmente si sientes que tenéis muchos puntos en común pero a diario sientes necesitas encontrar algo más. Es preciso que aclares tus sentimientos y tengas una conversación sincera con tu chico. Y si estás sentimentalmente libre y has conocido recientemente a una persona con la que te sientes a gusto a diario pero no te has planteado todavía una relación seria, hoy tendrá un gesto hacia ti que hará caer todas las barreras, Capricornio. Te enamorará con su actitud y sus palabras. Si le aceptas, vuestra relación tiene un gran futuro. También es buen momento para vivir un romance corto pero muy romántico."; 
        if ($_REQUEST['cod']==11) 
            echo "<strong>Acuario:</strong>No caigas en la rutina, Acuario, busca la forma de conseguir que el día de hoy sea espectacular, distinto a lo que estás acostumbrada a diario. Empieza por enfocar ciertos temas, en especial los laborales, con más optimismo del que acostumbras. Un cambio de actitud te beneficiará a ti y también a los de tu entorno. Aunque te cueste creerlo, esto siempre se hace notar en las altas esferas y generalmente las consecuencias son muy positivas. Todo lo contrario sucede si acudes al trabajo en plan “no puedo más” o “siempre me toca a mi”. Pruébalo y convéncete. En el amor, en cambio, te esperan hoy muy buenos momentos, especialmente si expresas lo que sientes por tu chico, Acuario. Tu actitud a diario puede haberle hecho creer que te estás enfriando, o que todo ha entrado en la rutina. Una sorpresita a tiempo suele hacer milagros y parece que estáis necesitando un revulsivo que os devuelva la ilusión y la pasión. Está en tus manos."; 
        if ($_REQUEST['cod']==12) 
            echo "<strong>Piscis:</strong>Procura hoy prestar atención a las muchas cosas bonitas que te rodean a diario, Piscis. Mantén una actitud positiva porque hoy te va a hacer falta. Es probable que descubras por casualidad que alguien te ocultó un hecho, una conversación, o algún detalle que a ti te hubiese interesado conocer para poder gestionar mejor tus cosas a diario. Si hablas hoy con la persona interesada, probablemente niegue tener este conocimiento, pero no bajes la guardia y defiende tu postura. Dale pistas para que se dé cuenta de que no se trata de una suposición, sino de algo que has comprobado. Verás con esto si tiene la honestidad de asumirlo y disculparse por su error. Si no es así y se mantiene en sus trece, asegurando que lo ignoraba, reconsidera seguir con esta amistad porque con amigos así no necesitarás nunca enemigos, Piscis. En el terreno sentimental, apoya mucho a tu pareja, lo está necesitando y él sí que se lo merece."; 
?>
